"""create initial schemas

Revision ID: 36d4e6b18ff5
Revises: 
Create Date: 2026-09-16 13:55:47.901047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d4e6b18ff5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer1', sa.String(), nullable=False),
    sa.Column('answer2', sa.String(), nullable=False),
    sa.Column('answer3', sa.String(), nullable=False),
    sa.Column('answer4', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('topic', sa.Enum('GEOGRAPHY', 'HISTORY', 'CURRENT_AFFAIRS', 'MOVIES', 'FOOD', name='topics', native_enum=False), nullable=False),
    sa.Column('level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='levels', native_enum=False), nullable=False),
    sa.Column('fact', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('session',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('topic', sa.Enum('GEOGRAPHY', 'HISTORY', 'CURRENT_AFFAIRS', 'MOVIES', 'FOOD', name='topics', native_enum=False), nullable=False),
    sa.Column('level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='levels', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='status', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('attempt',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_answer', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('attempt_id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_session_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempt')
    op.drop_table('session')
    op.drop_table('question')
    # ### end Alembic commands ###
